<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity' => 'فعالیت',
    'Add Comment' => 'افزودن نظر',
    'Add New User' => 'افزودن کاربر جدید',
    'Add This User To Team' => 'اضافه کردن این کاربر به تیم',
    'Add an item' => 'افزودن یک آیتم',
    'Archive' => 'بایگانی',
    'Archive List' => 'بایگانی لیست',
    'Archive This List' => 'بایگانی این لیست',
    'Attachment' => 'پیوست',
    'Attachments' => 'پیوست‌ها',
    'Board Title' => 'عنوان تخته',
    'Boards' => 'تخته‌ها',
    'Change Role To Admin' => 'تغییر نقش به مدیر',
    'Change Role To User' => 'تغییر نقش به کاربر',
    'Check List' => 'لیست بررسی',
    'Comments' => 'نظرات',
    'Create' => 'ایجاد',
    'Create Labels' => 'ایجاد برچسب‌ها',
    'Create New Board' => 'ایجاد تخته جدید',
    'Create New Team' => 'ایجاد تیم جدید',
    'Create Team Board' => 'ایجاد تخته تیم',
    'Create a new label' => 'ایجاد یک برچسب جدید',
    'Delete' => 'حذف',
    'Delete This Member' => 'حذف این عضو',
    'Delete This Team' => 'حذف این تیم',
    'Delete This User From Team' => 'حذف این کاربر از تیم',
    'Description' => 'توضیحات',
    'Dou Date' => 'تاریخ انجام',
    'Download' => 'دانلود',
    'Due Date' => 'تاریخ سررسید',
    'Email' => 'ایمیل',
    'Enter New Project Status Title' => 'وارد کردن عنوان وضعیت جدید پروژه',
    'Enter New Task Title' => 'وارد کردن عنوان وظیفه جدید',
    'Full Name' => 'نام کامل',
    'Label Title' => 'عنوان برچسب',
    'Labels' => 'برچسب‌ها',
    'Member' => 'عضو',
    'Members' => 'اعضا',
    'Menu' => 'منو',
    'Not Result' => 'نتیجه‌ای یافت نشد',
    'Notification' => 'اعلان',
    'Please Fill Form' => 'لطفاً فرم را پر کنید',
    'Private Board' => 'تخته خصوصی',
    'Projects' => 'پروژه‌ها',
    'Public Board' => 'تخته عمومی',
    'Remove' => 'حذف',
    'Role' => 'نقش',
    'Role Is Admin' => 'نقش: مدیر',
    'Role Is User' => 'نقش: کاربر',
    'Save' => 'ذخیره',
    'Search Members' => 'جستجوی اعضا',
    'Search Team' => 'جستجوی تیم',
    'Search User' => 'جستجوی کاربر',
    'Search label' => 'جستجوی برچسب',
    'Search members' => 'جستجوی اعضا',
    'Select Color' => 'انتخاب رنگ',
    'Select file to upload' => 'انتخاب فایل برای آپلود',
    'Show Menu' => 'نمایش منو',
    'Show Task Archive' => 'نمایش آرشیو وظایف',
    'Team' => 'تیم',
    'Team Title' => 'عنوان تیم',
    'Teams' => 'تیم‌ها',
    'This card has a description.' => 'این کارت دارای توضیحات است.',
    'Title Check List' => 'عنوان لیست بررسی',
    'Update' => 'به‌روزرسانی',
    'Update Description' => 'به‌روزرسانی توضیحات',
    'Update Project' => 'به‌روزرسانی پروژه',
    'Update Title' => 'به‌روزرسانی عنوان',
    'User Name' => 'نام کاربری',
    'Users' => 'کاربران',
    'View This Team' => 'مشاهده این تیم',
    'Watch' => 'پیگیری',
    'You are watching this card.' => 'شما در حال مشاهده این کارت هستید.',
];
